#!/usr/bin/env python3
"""Build an authoritative per-command flag inventory for CLI 2.0.0 GA.

Wave C has to fill Type, Required, Default and Notes columns for flag tables whose
current shape does not carry them. Guessing those values would put wrong facts
into published docs, so they are read from the packages the CLI actually ships.

Source of truth: the `oclif.manifest.json` that every published Contentstack CLI
plugin includes in its npm tarball. That file is generated by oclif from the
compiled command classes at publish time, so it is exactly what the released
binary exposes. `npm pack` retrieves it without needing a build, an install, or
the repo.

Why not the local repo. `repo/cli-plugins` sits on branch `v2-dev` with no
`v2.0.0` tag, so its working tree is not GA. Parsing its TypeScript produced
flag data that disagreed with the shipped packages, which is how the short-flag
discrepancy recorded below was found. The local repo is still parsed, but only as
a cross-check that reports disagreements rather than as a source.

Read-only apart from the report it writes, plus a tarball cache under the
scratchpad. No CMS access.

Usage:
  python3 scripts/gen_flag_inventory.py           # use cache if present
  python3 scripts/gen_flag_inventory.py --refetch # re-download every tarball
"""

import glob
import json
import os
import shutil
import subprocess
import sys
import tarfile
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "notes", "reports", "flag-inventory.json")
CACHE = os.path.join(tempfile.gettempdir(), "cli-ga-manifests")

# The 13 Contentstack plugins bundled at GA, read from
# `git -C repo/cli-core show v2.0.0:packages/contentstack/package.json`, plus the
# external plugins the docs cover. Versions are pinned so a later plugin release
# cannot silently change what this reports about GA.
BUNDLED = {
    "@contentstack/cli-config": "2.0.0",
    "@contentstack/cli-auth": "2.0.0",
    "@contentstack/cli-cm-import": "2.0.0",
    "@contentstack/cli-cm-export": "2.0.0",
    "@contentstack/cli-cm-seed": "2.0.0",
    "@contentstack/cli-cm-bootstrap": "2.0.0",
    "@contentstack/cli-cm-export-to-csv": "2.0.0",
    "@contentstack/cli-cm-clone": "2.0.0",
    "@contentstack/cli-migration": "2.0.0",
    "@contentstack/cli-cm-branches": "2.0.0",
    "@contentstack/cli-audit": "2.0.0",
    "@contentstack/cli-cm-import-setup": "2.0.0",
    "@contentstack/cli-bulk-operations": "2.0.0",
}

# Not in the GA bundle. A doc covering one of these needs a plugins:install step,
# per CMD2, so the bundled flag travels with the inventory.
EXTERNAL = {
    # cli-launch never reached 2.0.0. 1.11.2 is its latest published version, so
    # a doc claiming a 2.x launch plugin is wrong.
    "@contentstack/cli-launch": "1.11.2",
    "@contentstack/cli-cm-migrate-rte": "2.0.0",
    "@contentstack/apps-cli": "2.0.0",
    "contentstack-cli-tsgen": "5.0.0",
    "contentstack-cli-content-type": "2.0.0",
    "@contentstack/cli-variants": "2.0.0",
    "@contentstack/cli-external-migrate": "2.0.0",
    "@contentstack/cli-cm-regex-validate": "2.0.0",
    "@contentstack/cli-cm-export-query": "2.0.0",
    "@contentstack/cli-asset-management": "1.0.0",
}

# Three published plugins ship no oclif.manifest.json in their tarball, so their
# flags cannot be read from a released artifact at all. Their commands are absent
# from this inventory rather than filled in from the v2-dev working tree, because
# working-tree data is what produced the short-flag error this file exists to
# prevent. A Wave C table for one of these commands needs a human against
# `csdx <command> --help`.
NO_MANIFEST = ["@contentstack/apps-cli", "@contentstack/cli-launch",
               "@contentstack/cli-variants"]

# The last 1.x release of each plugin the changelog says removed short flags.
# "Removed" is a claim about a CHANGE, so it can only be tested by comparing two
# versions. Testing whether 2.0.0 has any short flags at all tests a different and
# much stronger proposition, and reports a real partial removal as a fabrication.
PREVIOUS_MAJOR = {
    "@contentstack/cli-cm-export": "1.27.1",
    "@contentstack/cli-cm-import": "1.35.1",
    "contentstack-cli-content-type": "1.5.5",
}


def fetch(package, version, refetch=False):
    """Extract one published package's oclif.manifest.json, or None."""
    os.makedirs(CACHE, exist_ok=True)
    safe = package.replace("/", "__").replace("@", "")
    dest = os.path.join(CACHE, f"{safe}-{version}")
    manifest_path = os.path.join(dest, "package", "oclif.manifest.json")
    if refetch and os.path.isdir(dest):
        shutil.rmtree(dest)
    if os.path.exists(manifest_path):
        return json.load(open(manifest_path, encoding="utf-8"))
    os.makedirs(dest, exist_ok=True)
    proc = subprocess.run(["npm", "pack", f"{package}@{version}", "--silent"],
                          cwd=dest, capture_output=True, text=True)
    if proc.returncode != 0:
        return None
    tgz = sorted(glob.glob(os.path.join(dest, "*.tgz")))
    if not tgz:
        return None
    with tarfile.open(tgz[0]) as tf:
        members = [m for m in tf.getmembers()
                   if m.name.endswith("oclif.manifest.json")]
        if not members:
            return None
        tf.extract(members[0], dest, filter="data")
        extracted = os.path.join(dest, members[0].name)
    return json.load(open(extracted, encoding="utf-8"))


def notes_for(flag):
    """The Notes cell, built only from facts the manifest states."""
    notes = []
    for other in flag.get("exclusive") or []:
        notes.append(f"Mutually exclusive with --{other}")
    for other in flag.get("dependsOn") or []:
        notes.append(f"Requires --{other}")
    if flag.get("multiple"):
        notes.append("Repeatable")
    if flag.get("options"):
        notes.append("One of: " + ", ".join(flag["options"]))
    return ". ".join(notes)


def doc_type(flag):
    """The Type cell. oclif reports 'option' for every value-taking flag, which
    is not a type a reader can act on, so it is resolved to what the flag holds."""
    if flag.get("type") == "boolean":
        return "boolean"
    if flag.get("multiple"):
        return "string[]"
    return "string"


def default_cell(flag):
    """The Default cell. `-` means the flag has no default, which is a fact worth
    stating rather than an empty cell that reads as an omission."""
    if "default" not in flag or flag["default"] is None:
        return "-"
    value = flag["default"]
    if isinstance(value, bool):
        return f"`{str(value).lower()}`"
    return f"`{value}`"


def build(refetch=False):
    commands = {}
    missing = []
    for package, version in sorted({**BUNDLED, **EXTERNAL}.items()):
        manifest = fetch(package, version, refetch)
        if manifest is None:
            missing.append(f"{package}@{version}")
            continue
        bundled = package in BUNDLED
        for cid, cmd in (manifest.get("commands") or {}).items():
            flags = {}
            for name, flag in (cmd.get("flags") or {}).items():
                flags[name] = {
                    "type": doc_type(flag),
                    "required": "Yes" if flag.get("required") else "No",
                    "default": default_cell(flag),
                    "short": f"-{flag['char']}" if flag.get("char") else None,
                    "hidden": bool(flag.get("hidden")),
                    "description": " ".join((flag.get("description") or "").split()),
                    "notes": notes_for(flag),
                }
            commands[cid] = {
                "package": package,
                "package_version": manifest.get("version") or version,
                "bundled_at_ga": bundled,
                "install": None if bundled else f"csdx plugins:install {package}",
                "description": " ".join((cmd.get("description") or "").split()),
                "examples": cmd.get("examples") or [],
                "flags": flags,
            }
    return commands, missing


# --------------------------------------------------------------------------
# GA claim verification
# --------------------------------------------------------------------------

# Each claim from changelog/2.x/cli-2.0.0.md that can be checked against a
# manifest. The changelog is a human-written release note. The manifest is
# generated from the shipped code. Where they disagree, the manifest wins.
GA_CLAIMS = [
    ("Short flags removed from cm:stacks:export",
     "cm:stacks:export", "some-short-flags-removed"),
    ("Short flags removed from cm:stacks:import",
     "cm:stacks:import", "some-short-flags-removed"),
    ("Short flags removed from content-type:list",
     "content-type:list", "some-short-flags-removed"),
    ("Short flags removed from content-type:diagram",
     "content-type:diagram", "some-short-flags-removed"),
    ("tsgen short flags -o, -p, -d removed",
     "tsgen", "absent:o,p,d"),
    ("tsgen --token-alias renamed to --alias",
     "tsgen", "absent-flag:token-alias"),
    ("--api-version removed from cm:stacks:bulk-entries",
     "cm:stacks:bulk-entries", "absent-flag:api-version"),
    ("--api-version removed from cm:stacks:bulk-taxonomies",
     "cm:stacks:bulk-taxonomies", "absent-flag:api-version"),
    ("New --skip-taxonomy-publish on import",
     "cm:stacks:import", "present-flag:skip-taxonomy-publish"),
    ("New --cs-assets on config:set:region",
     "config:set:region", "present-flag:cs-assets"),
    ("New --auth-api on config:set:region",
     "config:set:region", "present-flag:auth-api"),
    ("New command auth:tokens:list",
     "auth:tokens:list", "command-exists"),
    ("New command cm:stacks:bulk-taxonomies",
     "cm:stacks:bulk-taxonomies", "command-exists"),
]


def previous_short_flags(refetch=False):
    """{command_id: set(short chars)} from the last 1.x release of each plugin."""
    baseline = {}
    for package, version in PREVIOUS_MAJOR.items():
        manifest = fetch(package, version, refetch)
        if manifest is None:
            continue
        for cid, cmd in (manifest.get("commands") or {}).items():
            baseline[cid] = {f["char"] for f in (cmd.get("flags") or {}).values()
                             if f.get("char")}
    return baseline


def verify_claims(commands, baseline=None):
    baseline = baseline or {}
    results = []
    for claim, cid, test in GA_CLAIMS:
        cmd = commands.get(cid)
        if cmd is None:
            results.append({"claim": claim, "command": cid,
                            "verdict": "UNVERIFIED", "detail": "no manifest"})
            continue
        flags = cmd["flags"]
        if test == "command-exists":
            verdict, detail = "TRUE", f"exists at {cmd['package_version']}"
        elif test == "some-short-flags-removed":
            now = {f["short"].lstrip("-") for f in flags.values() if f["short"]}
            was = baseline.get(cid)
            if was is None:
                verdict, detail = "UNVERIFIED", "no 1.x baseline for this command"
            else:
                removed = sorted(was - now)
                kept = sorted(was & now)
                verdict = "TRUE" if removed else "FALSE"
                detail = (f"removed {', '.join('-' + c for c in removed) or 'none'}"
                          f"  |  kept {', '.join('-' + c for c in kept) or 'none'}")
        elif test.startswith("absent-flag:"):
            name = test.split(":", 1)[1]
            verdict = "TRUE" if name not in flags else "FALSE"
            detail = f"--{name} {'absent' if name not in flags else 'still present'}"
        elif test.startswith("present-flag:"):
            name = test.split(":", 1)[1]
            verdict = "TRUE" if name in flags else "FALSE"
            detail = f"--{name} {'present' if name in flags else 'missing'}"
        elif test.startswith("absent:"):
            chars = {f"-{c}" for c in test.split(":", 1)[1].split(",")}
            shorts = {f["short"] for f in flags.values() if f["short"]}
            left = sorted(chars & shorts)
            verdict = "TRUE" if not left else "FALSE"
            detail = "all removed" if not left else f"still present: {', '.join(left)}"
        else:
            verdict, detail = "UNVERIFIED", "unknown test"
        results.append({"claim": claim, "command": cid,
                        "verdict": verdict, "detail": detail})
    return results


def main():
    refetch = "--refetch" in sys.argv
    commands, missing = build(refetch)
    total_flags = sum(len(c["flags"]) for c in commands.values())
    print(f"commands: {len(commands)}   flags: {total_flags}")
    if missing:
        print("\npackages with no retrievable manifest, so no flag data here:")
        for m in missing:
            known = any(m.startswith(p) for p in NO_MANIFEST)
            print(f"   {m}"
                  f"{'  (ships no manifest, expected)' if known else '  (UNEXPECTED, investigate)'}")

    baseline = previous_short_flags(refetch)
    claims = verify_claims(commands, baseline)
    print("\n=== GA changelog claims checked against the shipped manifests ===")
    print("    'removed' claims are tested as a 1.x to 2.0.0 delta, not as absence\n")
    for r in claims:
        mark = {"TRUE": "  ok  ", "FALSE": " WRONG", "UNVERIFIED": "  ??  "}[r["verdict"]]
        print(f"{mark} {r['claim'][:60]:62s} {r['detail']}")
    wrong = [r for r in claims if r["verdict"] == "FALSE"]
    print(f"\n{len(wrong)} of {len(claims)} changelog claims are contradicted by the "
          "packages the CLI actually ships.")
    partial = [r for r in claims if r["verdict"] == "TRUE" and "kept" in r["detail"]
               and "kept none" not in r["detail"]]
    if partial:
        print(f"{len(partial)} claim(s) are TRUE but only partially, so the changelog "
              "wording overstates them:")
        for r in partial:
            print(f"  {r['command']}: {r['detail']}")

    report = {
        "cli_version": "2.0.0",
        "source_of_truth": "oclif.manifest.json inside each published npm tarball",
        "why_not_local_repo": ("repo/cli-plugins is on branch v2-dev with no v2.0.0 "
                               "tag, so its working tree is not GA"),
        "ga_claim_verification": claims,
        "packages_missing_manifest": missing,
        "commands": commands,
    }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump(report, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    print(f"wrote {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    main()
