#!/usr/bin/env python3
"""WI-3: run the doc-standards linter over all 82 CLI docs and aggregate.

Read-only. Writes one report.

Usage:
  python3 scripts/gen_section_order_report.py
"""

import collections
import glob
import json
import os
import re
import subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MD = os.path.join(ROOT, "docs", "markdown")
LINT = os.path.join(ROOT, "doc-standards", "scripts", "lint-doc.js")
OUT = os.path.join(ROOT, "notes", "reports", "cli-section-order-report.md")

# Research 4.7: both are zero-H2 stubs that no Section Order table can apply to.
# They are retire-or-merge candidates, reported rather than linted.
EXCLUDE = {"Useful Plugins.md", "Uninstall CLI Plugins.md"}


def esc(s):
    return str(s).replace("|", "\\|")


def fence_aware_headings(path):
    out, fence = [], False
    for n, line in enumerate(open(path, encoding="utf-8"), 1):
        if line.strip().startswith("```"):
            fence = not fence
            continue
        if fence:
            continue
        m = re.match(r"^(#{1,6})\s+(.*)$", line)
        if m:
            out.append((len(m.group(1)), m.group(2).strip(), n))
    return out


def main():
    files = sorted(
        f for f in glob.glob(MD + "/**/*.md", recursive=True)
        if "/Version 1" in f or "/Version 2" in f
    )
    linted, excluded = [], []
    for f in files:
        if os.path.basename(f) in EXCLUDE:
            excluded.append(f)
            continue
        p = subprocess.run(["node", LINT, f, "--format=json"],
                           capture_output=True, text=True)
        try:
            d = json.loads(p.stdout)
        except Exception:
            linted.append({"file": f, "type": "PARSE-FAIL", "errors": 0,
                           "flagged": 0, "findings": [], "flags": []})
            continue
        linted.append({
            "file": f,
            "type": d.get("type"),
            "errors": d.get("summary", {}).get("errors", 0),
            "flagged": d.get("summary", {}).get("warnings", 0),
            "findings": d.get("automatedFindings", []),
            "flags": d.get("flagged", []),
        })

    by_type = collections.Counter(r["type"] for r in linted)
    by_rule = collections.Counter()
    for r in linted:
        for fi in r["findings"]:
            by_rule[fi.get("ruleId")] += 1
    flag_by_rule = collections.Counter()
    for r in linted:
        for fi in r["flags"]:
            flag_by_rule[fi.get("ruleId")] += 1

    # Missing-section tally, straight from the section-structure messages.
    missing = collections.Counter()
    for r in linted:
        for fi in r["findings"]:
            m = re.match(r'Required section "([^"]+)" is missing', fi.get("message", ""))
            if m:
                missing[(r["type"], m.group(1))] += 1

    total_err = sum(r["errors"] for r in linted)
    L = []
    A = L.append
    A("# CLI Section Order and Consistency Report")
    A("")
    A("WI-3 of the CLI Structure Review. Generated by running the doc-standards linter "
      "over every CLI doc with the three CLI types added in WI-2.")
    A("")
    A("Reproduce with:")
    A("")
    A("```bash")
    A("python3 scripts/gen_section_order_report.py")
    A("```")
    A("")
    A("## What was linted")
    A("")
    A("| Measure | Count |")
    A("|---|---|")
    A(f"| Docs in scope | {len(files)} |")
    A(f"| Linted | {len(linted)} |")
    A(f"| Excluded as untypable stubs | {len(excluded)} |")
    A(f"| Total tier-1 errors | {total_err} |")
    A(f"| Total tier-2 flags | {sum(r['flagged'] for r in linted)} |")
    A("")
    A("### Type assignment")
    A("")
    A("| Doc type | Docs |")
    A("|---|---|")
    for t, n in by_type.most_common():
        A(f"| `{t}` | {n} |")
    A("")
    A("Type detection keys off each doc's subject rather than its current structure. "
      "That is deliberate: typing a doc by the sections it already has would mean a doc "
      "missing its `Commands` section gets typed as something that does not need one, so "
      "the omission would never be reported.")
    A("")
    A("### Excluded")
    A("")
    for f in excluded:
        A(f"- `{esc(os.path.relpath(f, MD))}` has zero H2 headings, so no Section Order "
          "table can apply. Reported as a retire-or-merge candidate rather than linted.")
    A("")
    A("---")
    A("")
    A("## What the numbers mean")
    A("")
    A("Five findings account for most of the total. Each is one decision, not hundreds "
      "of edits.")
    A("")
    A("### 1. The flag table has no agreed shape (CLI-01, 167 occurrences)")
    A("")
    A("CLI-C2 mandates `Flag | Type | Required | Default | Description | Notes`. "
      "**16 distinct column signatures are in use and no table matches the mandated "
      "shape.** The three most common are:")
    A("")
    A("| Signature | Tables |")
    A("|---|---|")
    A("| `option \\| type \\| default \\| description` | 58 |")
    A("| `option \\| type \\| default \\| required \\| description` | 48 |")
    A("| `flag \\| short flag \\| description` | 29 |")
    A("")
    A("The count did not move when the mandated shape went from four columns to six, "
      "and that is worth reading correctly. CLI-01 counts a table once if it is missing "
      "any required column, so a table already failing on `flag` and `notes` keeps "
      "failing on the same two. What changed is the size of the fix per table, and it "
      "got smaller: the 48 tables carrying `option | type | default | required | "
      "description` now need a header rename and one added column, rather than dropping "
      "the Type and Default they already populate. 106 of the 167 tables carry Type and "
      "Default today, which is why the old four-column shape appeared on exactly one "
      "table in 82 docs.")
    A("")
    A("The two `option`-led signatures sit almost entirely in `Contentstack CLI "
      "Configuration Reference`, where `Option` means a config-file key rather than a "
      "CLI flag. That naming clash is worth settling before the tables are converted, "
      "because the module reference and the command references are describing different "
      "things with the same word.")
    A("")
    A("### 2. Most docs have no Overview, Examples, Troubleshooting, or Next Steps "
      "(C1-01, 301)")
    A("")
    A("36 of 43 command references have no `Overview` heading. Nearly all of them do "
      "have intro prose, it just sits untitled between the H1 and the first H2, so it is "
      "invisible to the page navigation and to any structural check. This is the cheapest "
      "large win in the report: adding a heading above existing text.")
    A("")
    A("`Next Steps` is missing from 35 of 43 command references and 23 of 24 runbooks. "
      "`Troubleshooting` from 32 and 16. `Limitations` from 26 and 18, which matters most "
      "on runbooks, because those are the docs that overwrite and delete stack content.")
    A("")
    A("**`Examples` is new to this count, and it is the one line that is not free.** "
      "36 of 43 command references lack it, and unlike `Overview` there is usually no "
      "existing text to put a heading over. It was promoted from Recommended to Required "
      "deliberately: only a cell beginning with the word \"Required\" is machine-enforced, "
      "so a Recommended section is advisory and gets dropped under time pressure. Four of "
      "the 36 have an Examples heading at H3 or deeper and need only a promotion. The "
      "other 32 need examples written.")
    A("")
    A("### 3. 179 headings are too deep to link to (CLI-05, 179)")
    A("")
    A("Every H4 or deeper heading in the corpus. CLI-C1 stops CLI headings at H3, "
      "because the renderer emits an anchor id and a right-hand navigation entry for H2 "
      "and H3 only. An H4 cannot be deep-linked from any other doc and is absent from "
      "its own page's navigation, whatever it contains. The fix is a promotion to H3 "
      "where the content needs to be linked to, and a bold lead-in where it does not.")
    A("")
    A("**This number replaces an earlier count of 18, and the difference is a "
      "deliberate reversal rather than a correction.** The first version of this check "
      "flagged only H4s that named a command, and exempted facet headings such as "
      "Syntax, Flags, Output and Examples on the grounds that they described the command "
      "above them. That exemption is gone. A facet at H4 is exactly as unlinkable as a "
      "command at H4, and CMD1 now specifies bold lead-ins for facets. The check also "
      "runs on every CLI doc now, not only on docs carrying one of the three CLI types, "
      "because the constraint comes from the rendering platform rather than from a "
      "template.")
    A("")
    A("| Doc | H4s | What they are |")
    A("|---|---|---|")
    A("| `Migrate from Contentstack CLI V1 to V2 \\| V2.x.x` | 43 | `Removed Flags` "
      "repeated 22 times, plus per-command detail. Typed `migration-guide`, so it was "
      "invisible to the old check entirely |")
    A("| `Content Type Plugin`, both versions | 24 each | Syntax, Flags, Output, "
      "Examples facets of 6 commands. Previously exempt |")
    A("| `Create Custom CLI Plugins for Contentstack \\| V2.x.x` | 18 | |")
    A("| `Bulk Operations in CLI \\| V2.x.x` | 15 | |")
    A("| `CLI Authentication and Adding Tokens`, both versions | 7 each | The seven "
      "`auth:*` procedures |")
    A("")
    A("**The 18 findings the old check reported are still the highest-value subset**, "
      "and WI-4 found the same defect independently from the link side. "
      "`CLI Authentication and Adding Tokens`, in both versions, documents all seven "
      "`auth:*` procedures at H4: Login, Logout, Display Username of the Logged in User, "
      "Add Management Token, Add Delivery Token, Delete Token, List All Tokens. Since "
      "`#login` and `#add-management-token` are part of the Prerequisites boilerplate "
      "most command docs copy, this single page breaks 26 inbound links across the "
      "corpus. `CLI for Launch` adds 2 more per version, including a `Prerequisites` at "
      "H4. Promoting four headings in that one doc, in both versions, is still the "
      "cheapest fix in this report.")
    A("")
    A("### 4. Troubleshooting entries are not in the mandated format (C1-05, 66)")
    A("")
    A("Each entry needs a symptom heading, then a bolded Root Cause label, then a bolded "
      "Resolution label. 66 entries are missing one or both.")
    A("")
    A("A linter bug was fixed as part of this run, and it matters for interpreting the "
      "number: `checks/troubleshooting-format.js` previously required the literal "
      "`**Root Cause(s)**`, while `common-rules.md` mandates `**Root Cause**` or "
      "`**Root Causes**`. Every doc that followed the written standard was failing a "
      "tier-1 check. All three spellings are accepted now, so these 66 are real.")
    A("")
    A("### 5. Two conventions were never settled (C3-05 37, C8-07 33, CLI-06)")
    A("")
    A("37 em dashes or semicolons in prose, against a hard rule that forbids them. 33 "
      "acronyms used before being expanded. And every code fence in the corpus, 1,782 of "
      "them, carries no language tag, reported at tier 2 because it is one mechanical "
      "pass rather than a judgment call per doc.")
    A("")
    A("### No doc is currently clean")
    A("")
    A("Zero of the 78 linted docs pass with no tier-1 error. That is expected on first "
      "contact with a new standard and is not an argument against the standard. The "
      "distribution is what matters, because it gives a clear order to work in.")
    A("")
    A("| | Errors | Doc |")
    A("|---|---|---|")
    A("| Cleanest | 1 | `Asset Scanning in CLI \\| V1.x.x` |")
    A("| | 2 | `Change Master Locale` (both versions), `Install the CLI \\| V1.x.x` |")
    A("| Worst | 64 | `Contentstack CLI Configuration Reference` (one entry, shown in "
      "both version trees) |")
    A("| | 60 | `Migrate from Contentstack CLI V1 to V2 \\| V2.x.x` |")
    A("| | 53 | `Bulk Operations in CLI \\| V2.x.x` |")
    A("| | 44 | `Bulk Operations in CLI \\| V1.x.x` |")
    A("")
    A("The three worst are worth naming, because they are three different problems. "
      "`Contentstack CLI Configuration Reference` scores 64 almost entirely on CLI-01: "
      "it is 1,145 lines of option tables in a shape the standard does not recognise, "
      "and converting those tables is nearly the whole fix. `Migrate from Contentstack "
      "CLI V1 to V2` scores 60 almost entirely on CLI-05, from 43 H4s, and it is new to "
      "this list because the heading-depth check now reaches docs typed "
      "`migration-guide`. `Bulk Operations in CLI` scores 53 on genuine structural "
      "sprawl: a `## Overview` followed by a Q and A heading, a forbidden `Quick Start`, "
      "11 numbered use cases, a `Best Practices` section, and no Prerequisites, "
      "Limitations, or Next Steps. The first two need mechanical passes. The third needs "
      "a rewrite.")
    A("")
    A("---")
    A("")
    A("## Findings by rule")
    A("")
    A("Tier 1 is a hard error. Tier 2 is advisory.")
    A("")
    A("| Rule | Tier | Occurrences |")
    A("|---|---|---|")
    for rid, n in by_rule.most_common():
        A(f"| `{rid}` | 1 | {n} |")
    for rid, n in flag_by_rule.most_common():
        A(f"| `{rid}` | 2 | {n} |")
    A("")
    A("---")
    A("")
    A("## Missing required sections, by type")
    A("")
    A("This is the core structural finding. Each row is a section the type requires and "
      "the number of docs of that type that lack it.")
    A("")
    A("| Doc type | Missing section | Docs affected |")
    A("|---|---|---|")
    for (t, sec), n in sorted(missing.items(), key=lambda kv: (-kv[1], kv[0])):
        A(f"| `{t}` | {sec} | {n} |")
    A("")
    A("---")
    A("")
    A("## Per-doc detail")
    A("")
    A("| Doc | Type | Errors | Flags | Rules triggered |")
    A("|---|---|---|---|---|")
    for r in sorted(linted, key=lambda x: (-x["errors"], x["file"])):
        rules = sorted({fi.get("ruleId") for fi in r["findings"]})
        A("| `%s` | `%s` | %d | %d | %s |" % (
            esc(os.path.relpath(r["file"], MD).replace(".md", "")),
            r["type"], r["errors"], r["flagged"],
            ", ".join("`%s`" % x for x in rules) if rules else "none"))
    A("")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w").write("\n".join(L) + "\n")
    print("wrote", OUT)
    print("linted %d, excluded %d, total errors %d" % (len(linted), len(excluded), total_err))
    print("types:", dict(by_type))
    print("top rules:", by_rule.most_common(12))


if __name__ == "__main__":
    main()
